version: '3'
services:
  echo:
    image: ubuntu:latest
    command: ["sh", "-c", "apt-get update && apt-get install -y ncat && ncat -l -p 1234 -k -e /bin/cat"]
    name: "echo_server_compose"
    ports:
      - "1235:1234"
